### ISSUE TITLE
Enhance the landing page

### ISSUE THREAD

**Issue by everly-gif** [aUnicornDev/tabsMonster#4]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Right now, the landing page is pretty empty , having a webpage with the extension's previews and features would be great

**Describe the solution you'd like**
I would like to take over the landing page's development, creating a minimalistic design and develop it.

**Describe alternatives you've considered**
I could also break the webpage into various sections and create issues for other contributors to contribute and just focus on developing one particular section, rather than single handedly doing all of them . It will be beneficial for the repo.

**Additional context**

**Comment by everly-gif** [comment]
I would like to help in any way ! let me know your suggestions

**Comment by aUnicornDev** [comment]
Hey, Thank you for opening the issue. I have some ideas regarding the sections of the landing page.. How can we connect? Want to move this to Github discussions?

**Comment by everly-gif** [comment]
sure let's do it
