### ISSUE TITLE
[Feature] Create the popup in HTML & CSS for the extension

### ISSUE THREAD

**Issue by aUnicornDev** [aUnicornDev/tabsMonster#6]
**Is your feature request related to a problem? Please describe.**
Convert the mockup for the Extension into HTML-CSS.
Try and stick to CSS and SASS.

**Describe the solution you'd like**
The popup should resemble the design given in the following [Figma](https://www.figma.com/file/H55fANLsznxEkazJTV2TCA/tabsMonster?node-id=2%3A3) file.

*Look for the Desktop Final Board in the Figma File*

The colors will be added later so make it grayscale as it is.
Please suggest more themes because we are short on it.

**Comment by pratikkarelia25** [comment]
@aUnicornDev can you just check the pull request I've opened?

**Comment by aUnicornDev** [comment]
Hey @pratikkarelia25 , are you still interested in this issue.. I've made some changes to the designs
