### ISSUE TITLE
[Enhancement] Add More theme ideas to Themes.md

### ISSUE THREAD

**Issue by aUnicornDev** [aUnicornDev/tabsMonster#8]
**Is your feature request related to a problem? Please describe.**
Add more themes for the extension for the user to choose from.

**Describe the solution you'd like**
These themes will be put into a database and the users can switch between the themes in the extension

**Additional context**
How to add themes is provided in the THEMES.md file

**Comment by parth-gpt** [comment]
I have been meaning to contribute here can anyone let me know what is meant by monster level over here in Themes.md?
